refactor:remove surplus file and fix find jar bug

diff --git a/bin/run-tpcds-benchmark b/bin/run-tpcds-benchmark
--- a/bin/run-tpcds-benchmark
+++ b/bin/run-tpcds-benchmark
@@ -18,13 +18,10 @@
 #
 
 #
-# Shell script for running TPCDS benchmarks
+# Shell script for validating TPCDS query results
 
 if [ -z "${SPARK_HOME}" ]; then
   echo "env SPARK_HOME not defined" 1>&2
-  exit 1
-elif [ ! -e "${SPARK_HOME}/pom.xml" ]; then
-  echo "You need to check out Spark from https://github.com/apache/spark" 1>&2
   exit 1
 fi
 
@@ -32,27 +29,36 @@ fi
 _DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 # Load common functions
-. "${_DIR}/utils.sh"
+#. "${_DIR}/utils.sh"
 
 # If Spark not compiled, do it here
-check_spark_compiled
+#check_spark_compiled
 
 # Do some preparations before launching spark-submit
-parse_args_for_spark_submit "$@"
+#parse_args_for_spark_submit "$@"
 
 # Resolve a jar location for the TPCDS data generator
-resolve_spark_scala_version() {
-  SCALA_VERSION=`grep "<scala.binary.version>" "${SPARK_HOME}/pom.xml" | head -n1 | awk -F '[<>]' '{print $3}'`
-  SPARK_VERSION=`grep "<version>" "${SPARK_HOME}/pom.xml" | head -n2 | tail -n1 | awk -F '[<>]' '{print $3}'`
+find_resource() {
+  local tpcds_datagen_version=`grep "<version>" "${_DIR}/../pom.xml" | head -n2 | tail -n1 | awk -F '[<>]' '{print $3}'`
+  local scala_version=`grep "<scala.binary.version>" "${_DIR}/../pom.xml" | head -n1 | awk -F '[<>]' '{print $3}'`
+  local jar_file="iceberg-spark-tpcds-${tpcds_datagen_version}-with-dependencies.jar"
+  local built_jar="$_DIR/../target/${jar_file}"
+  if [ -e "$built_jar" ]; then
+    RESOURCE=$built_jar
+  else
+    RESOURCE="$_DIR/../assembly/${jar_file}"
+    echo "${built_jar} not found, so use pre-compiled ${RESOURCE}" 1>&2
+  fi
 }
 
-resolve_spark_scala_version
+SPARK_VERSION=`echo ${SPARK_HOME} | awk -F '[-]' '{print $2}'`
 
+find_resource
 echo "Using \`spark-submit\` from path: $SPARK_HOME" 1>&2
 exec "${SPARK_HOME}"/bin/spark-submit                                  \
   --class org.apache.spark.sql.execution.benchmark.TPCDSQueryBenchmark \
-  --jars "$SPARK_HOME/core/target/spark-core_${SCALA_VERSION}-${SPARK_VERSION}-tests.jar,$SPARK_HOME/sql/catalyst/target/spark-catalyst_${SCALA_VERSION}-${SPARK_VERSION}-tests.jar" \
-  $(join_by " " ${SPARK_CONF[@]})                                      \
-  "$SPARK_HOME/sql/core/target/spark-sql_${SCALA_VERSION}-${SPARK_VERSION}-tests.jar" \
-  $(join_by " " ${ARGS[@]})
+  --jars "$_DIR/../assembly/spark-catalyst_2.12-${SPARK_VERSION}-tests.jar,$_DIR/../assembly/spark-sql_2.12-${SPARK_VERSION}-tests.jar,$_DIR/../assembly/spark-core_2.12-${SPARK_VERSION}-tests.jar,$_DIR/../assembly/iceberg-spark-runtime-3.2_2.12-0.13.1.jar" \
+  ${SPARK_CONF}                                      \
+  ${RESOURCE}                                        \
+  ${ARGS[@]}
 
